import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1790076153882 implements MigrationInterface {
    name = 'Migration1790076153882'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "fk_organizations_owner_user_id"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "fk_members_organization_id"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "fk_members_user_id"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "fk_roles_organization_id"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "fk_role_permissions_permission_id"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "fk_role_permissions_role_id"`);
        await queryRunner.query(`ALTER TABLE "organization_member_roles" DROP CONSTRAINT "fk_org_member_roles_role_id"`);
        await queryRunner.query(`ALTER TABLE "organization_member_roles" DROP CONSTRAINT "fk_org_member_roles_member_id"`);
        await queryRunner.query(`ALTER TABLE "organization_invites" DROP CONSTRAINT "fk_org_invites_role_id"`);
        await queryRunner.query(`ALTER TABLE "organization_invites" DROP CONSTRAINT "fk_org_invites_organization_id"`);
        await queryRunner.query(`DROP INDEX "public"."uq_roles_org_role_name"`);
        await queryRunner.query(`DROP INDEX "public"."uq_roles_system_role_name"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "stripe_customer_id" character varying`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "organizationSubscriptionId" uuid`);
        await queryRunner.query(`ALTER TYPE "public"."organization_type_enum" RENAME TO "organization_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."organizations_type_enum" AS ENUM('personal', 'team')`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "type" TYPE "public"."organizations_type_enum" USING "type"::"text"::"public"."organizations_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."organization_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."org_status_enum" RENAME TO "org_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."organizations_status_enum" AS ENUM('active', 'suspended', 'deleted')`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "status" TYPE "public"."organizations_status_enum" USING "status"::"text"::"public"."organizations_status_enum"`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."org_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."member_status_enum" RENAME TO "member_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."members_status_enum" AS ENUM('invited', 'active', 'removed')`);
        await queryRunner.query(`ALTER TABLE "members" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "members" ALTER COLUMN "status" TYPE "public"."members_status_enum" USING "status"::"text"::"public"."members_status_enum"`);
        await queryRunner.query(`ALTER TABLE "members" ALTER COLUMN "status" SET DEFAULT 'invited'`);
        await queryRunner.query(`DROP TYPE "public"."member_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "watch_history" DROP CONSTRAINT "FK_42e23cf9852981b38e9bbaa96a2"`);
        await queryRunner.query(`ALTER TABLE "watchlist_items" DROP CONSTRAINT "FK_06b4cbb683b730a8649447216fd"`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "organization_invites" DROP CONSTRAINT "uq_org_invites_token_hash"`);
        await queryRunner.query(`ALTER TYPE "public"."invite_status_enum" RENAME TO "invite_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."organization_invites_status_enum" AS ENUM('pending', 'accepted', 'expired', 'revoked')`);
        await queryRunner.query(`ALTER TABLE "organization_invites" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "organization_invites" ALTER COLUMN "status" TYPE "public"."organization_invites_status_enum" USING "status"::"text"::"public"."organization_invites_status_enum"`);
        await queryRunner.query(`ALTER TABLE "organization_invites" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."invite_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."plan_scope_enum" RENAME TO "plan_scope_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."plans_scope_enum" AS ENUM('individual', 'organization')`);
        await queryRunner.query(`ALTER TABLE "plans" ALTER COLUMN "scope" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "plans" ALTER COLUMN "scope" TYPE "public"."plans_scope_enum" USING "scope"::"text"::"public"."plans_scope_enum"`);
        await queryRunner.query(`ALTER TABLE "plans" ALTER COLUMN "scope" SET DEFAULT 'individual'`);
        await queryRunner.query(`DROP TYPE "public"."plan_scope_enum_old"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_org_invites_token_hash" ON "organization_invites" ("token_hash") `);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "chk_payments_exactly_one_subscription" CHECK (("userSubscriptionId" IS NOT NULL AND "organizationSubscriptionId" IS NULL) OR ("userSubscriptionId" IS NULL AND "organizationSubscriptionId" IS NOT NULL))`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "FK_da404b5fd9c390e25338996e2d1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "FK_40c051286e8db5b4613ecb3035a" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "watch_history" ADD CONSTRAINT "FK_42e23cf9852981b38e9bbaa96a2" FOREIGN KEY ("profile_id") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "watchlist_items" ADD CONSTRAINT "FK_06b4cbb683b730a8649447216fd" FOREIGN KEY ("profile_id") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_c328a1ecd12a5f153a96df4509e" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("permission_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_member_roles" ADD CONSTRAINT "FK_e447eaa9e3f84a455d2b92c913e" FOREIGN KEY ("member_id") REFERENCES "members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_member_roles" ADD CONSTRAINT "FK_8649b074f3877a1371a624695b1" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_invites" ADD CONSTRAINT "FK_86ee44dc17238efe40601b14540" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_invites" ADD CONSTRAINT "FK_01ecac90a28de2561019b9cad2a" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "organization_invites" DROP CONSTRAINT "FK_01ecac90a28de2561019b9cad2a"`);
        await queryRunner.query(`ALTER TABLE "organization_invites" DROP CONSTRAINT "FK_86ee44dc17238efe40601b14540"`);
        await queryRunner.query(`ALTER TABLE "organization_member_roles" DROP CONSTRAINT "FK_8649b074f3877a1371a624695b1"`);
        await queryRunner.query(`ALTER TABLE "organization_member_roles" DROP CONSTRAINT "FK_e447eaa9e3f84a455d2b92c913e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_c328a1ecd12a5f153a96df4509e"`);
        await queryRunner.query(`ALTER TABLE "watchlist_items" DROP CONSTRAINT "FK_06b4cbb683b730a8649447216fd"`);
        await queryRunner.query(`ALTER TABLE "watch_history" DROP CONSTRAINT "FK_42e23cf9852981b38e9bbaa96a2"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "FK_40c051286e8db5b4613ecb3035a"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "FK_da404b5fd9c390e25338996e2d1"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "chk_payments_exactly_one_subscription"`);
        await queryRunner.query(`DROP INDEX "public"."idx_org_invites_token_hash"`);
        await queryRunner.query(`CREATE TYPE "public"."plan_scope_enum_old" AS ENUM('individual', 'organization')`);
        await queryRunner.query(`ALTER TABLE "plans" ALTER COLUMN "scope" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "plans" ALTER COLUMN "scope" TYPE "public"."plan_scope_enum_old" USING "scope"::"text"::"public"."plan_scope_enum_old"`);
        await queryRunner.query(`ALTER TABLE "plans" ALTER COLUMN "scope" SET DEFAULT 'individual'`);
        await queryRunner.query(`DROP TYPE "public"."plans_scope_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."plan_scope_enum_old" RENAME TO "plan_scope_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."invite_status_enum_old" AS ENUM('pending', 'accepted', 'expired', 'revoked')`);
        await queryRunner.query(`ALTER TABLE "organization_invites" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "organization_invites" ALTER COLUMN "status" TYPE "public"."invite_status_enum_old" USING "status"::"text"::"public"."invite_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "organization_invites" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."organization_invites_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."invite_status_enum_old" RENAME TO "invite_status_enum"`);
        await queryRunner.query(`ALTER TABLE "organization_invites" ADD CONSTRAINT "uq_org_invites_token_hash" UNIQUE ("token_hash")`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "watchlist_items" ADD CONSTRAINT "FK_06b4cbb683b730a8649447216fd" FOREIGN KEY ("profile_id") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "watch_history" ADD CONSTRAINT "FK_42e23cf9852981b38e9bbaa96a2" FOREIGN KEY ("profile_id") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE TYPE "public"."member_status_enum_old" AS ENUM('invited', 'active', 'removed')`);
        await queryRunner.query(`ALTER TABLE "members" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "members" ALTER COLUMN "status" TYPE "public"."member_status_enum_old" USING "status"::"text"::"public"."member_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "members" ALTER COLUMN "status" SET DEFAULT 'invited'`);
        await queryRunner.query(`DROP TYPE "public"."members_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."member_status_enum_old" RENAME TO "member_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."org_status_enum_old" AS ENUM('active', 'suspended', 'deleted')`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "status" TYPE "public"."org_status_enum_old" USING "status"::"text"::"public"."org_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."organizations_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."org_status_enum_old" RENAME TO "org_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."organization_type_enum_old" AS ENUM('personal', 'team')`);
        await queryRunner.query(`ALTER TABLE "organizations" ALTER COLUMN "type" TYPE "public"."organization_type_enum_old" USING "type"::"text"::"public"."organization_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."organizations_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."organization_type_enum_old" RENAME TO "organization_type_enum"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "organizationSubscriptionId"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "stripe_customer_id"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_roles_system_role_name" ON "roles" ("role_name") WHERE (organization_id IS NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_roles_org_role_name" ON "roles" ("organization_id", "role_name") WHERE (organization_id IS NOT NULL)`);
        await queryRunner.query(`ALTER TABLE "organization_invites" ADD CONSTRAINT "fk_org_invites_organization_id" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_invites" ADD CONSTRAINT "fk_org_invites_role_id" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_member_roles" ADD CONSTRAINT "fk_org_member_roles_member_id" FOREIGN KEY ("member_id") REFERENCES "members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_member_roles" ADD CONSTRAINT "fk_org_member_roles_role_id" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_role_id" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_permission_id" FOREIGN KEY ("permission_id") REFERENCES "permissions"("permission_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "fk_roles_organization_id" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "fk_members_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "fk_members_organization_id" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "fk_organizations_owner_user_id" FOREIGN KEY ("owner_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
